// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[example]")
{
    REQUIRE(operaNumeros(10,20, "S") == 30);
    REQUIRE(operaNumeros(10,20, "R") == -10);
    REQUIRE(operaNumeros(10,20, "M") == 200);
    REQUIRE(operaNumeros(100,200, "S") == 300);
    REQUIRE(operaNumeros(100,200, "R") == -100);
    REQUIRE(operaNumeros(100,200, "M") == 2000);
}



